FROM python:3.11-slim

WORKDIR /app

COPY requirements/base.txt requirements.txt

RUN pip install --upgrade pip wheel && \
    pip install \
        --retries 10 \
        --timeout 600 \
        -r requirements.txt