# k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: {{ .Values.namespace}}
data:
  MLFLOW_TRACKING_URI: {{ .Values.configmap.mlflowTrackingUri}}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.configmap.mlflowS3EndpointUrl}}
  MODEL_NAME: {{ .Values.configmap.modelName}}
  MODEL_VERSION: {{ .Values.configmap.modelVersion}}
  GIT_PYTHON_REFRESH: {{ .Values.configmap.gitPythonRefresh}}