# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mlops-secret
  namespace: {{ .Values.namespace}}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.secret.minioRootUser}}
  MINIO_ROOT_PASSWORD: {{ .Values.secret.minioRootPassword}}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsAccessKeyId}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsSecretAccessKey}}
  GRAFANA_PASSWORD: {{ .Values.secret.grafanaPassword}}